/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Jungle_temple_ruined_portal;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
